name: Deploy to AKS
# Deploy to Azure Kubernetes Service
env:
  k8sclustername: kubeaks
  resourceGroupName: testkube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: '${{ env.k8sclustername }}'
        resource-group: '${{ env.resourceGroupName }}'

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          KubernetesManifest/nginx.yml
